// Generated by Haxe 4.1.0-rc.1+18b5e7d10
#include <hxcpp.h>

#ifndef INCLUDED_Main
#include <Main.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_e47a9afac0942eb9_12_new,"Main","new",0x6616a5cb,"Main.new","Main.hx",12,0x087e5c05)
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_4_main,"Main","main",0xed0e206e,"Main.main","Main.hx",4,0x087e5c05)

void Main_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_12_new)
            	}

Dynamic Main_obj::__CreateEmpty() { return new Main_obj; }

void *Main_obj::_hx_vtable = 0;

Dynamic Main_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Main_obj > _hx_result = new Main_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Main_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x07825a7d;
}

void Main_obj::main(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_4_main)
HXLINE(   5)		::haxe::Log_obj::trace(1,::hx::SourceInfo(HX_("src/Main.hx",9a,7a,30,a1),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXDLIN(   5)		::haxe::Log_obj::trace(2,::hx::SourceInfo(HX_("src/Main.hx",9a,7a,30,a1),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXDLIN(   5)		::haxe::Log_obj::trace(3,::hx::SourceInfo(HX_("src/Main.hx",9a,7a,30,a1),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXDLIN(   5)		::haxe::Log_obj::trace(4,::hx::SourceInfo(HX_("src/Main.hx",9a,7a,30,a1),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXDLIN(   5)		::haxe::Log_obj::trace(5,::hx::SourceInfo(HX_("src/Main.hx",9a,7a,30,a1),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXDLIN(   5)		::haxe::Log_obj::trace(6,::hx::SourceInfo(HX_("src/Main.hx",9a,7a,30,a1),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXDLIN(   5)		::haxe::Log_obj::trace(7,::hx::SourceInfo(HX_("src/Main.hx",9a,7a,30,a1),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXDLIN(   5)		::haxe::Log_obj::trace(8,::hx::SourceInfo(HX_("src/Main.hx",9a,7a,30,a1),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXDLIN(   5)		::haxe::Log_obj::trace(9,::hx::SourceInfo(HX_("src/Main.hx",9a,7a,30,a1),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(Main_obj,main,(void))


Main_obj::Main_obj()
{
}

bool Main_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *Main_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *Main_obj_sStaticStorageInfo = 0;
#endif

::hx::Class Main_obj::__mClass;

static ::String Main_obj_sStaticFields[] = {
	HX_("main",39,38,56,48),
	::String(null())
};

void Main_obj::__register()
{
	Main_obj _hx_dummy;
	Main_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("Main",59,64,2f,33);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Main_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Main_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< Main_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Main_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Main_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

